name: Clean singbox_ui GHCR Images

on:
  workflow_dispatch:   # 手动触发

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions of singbox_ui
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'singbox_ui'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
